name: optitest_example
description: OptiTest Example — demonstrates TestKey and Testable usage.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  optitest:
    path: ../

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
